### ISSUE TITLE
Revisão sobre os Requisitos

### ISSUE THREAD

**Issue by eduardolfalcao** [lumathias/NutriCare_Project#2]
- Falta escrever os casos de uso
- Falta escrever as USs
- Sugestões
> - Mudar as ações para gerenciar, para refletir o CRUD, como conversamos em sala
> - Ajustar a escrita do caso de uso "Diário alimentar" para refletir uma ação
- Organizem melhor o repo, colocando alguma descrição na página inicial do objetivo do projeto, e outras informações que provejam contexto

**Comment by lumathias** [comment]
Boa noite, prof.
Fizemos as alterações no repositório e colocamos as USs e os casos de uso. 
Gostaria de saber se as USs: 
> Como nutricionista, eu gostaria de adicionar medidas dos pacientes
> Como nutricionista, eu gostaria de gerenciar planos dos pacientes
poderiam ser colocadas na US de gerenciar paciente, e com isso não escrevê-las, só deixá-las "subentendidas"?
